﻿// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TRODHA.Infrastructure.Data;

#nullable disable

namespace TRODHA.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250417000000_AddAdminUser")]
    partial class AddAdminUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Burada model tanımlamaları olacak, ancak bu dosya otomatik olarak oluşturulduğu için
            // ve şu anda tam model tanımlamasına ihtiyacımız olmadığı için basitleştirilmiştir.
            // Migration uygulandığında EF Core bu dosyayı otomatik olarak güncelleyecektir.
#pragma warning restore 612, 618
        }
    }
}
